### ISSUE TITLE
Add SOCKS4/5, HTTPS proxy support

### ISSUE THREAD

**Issue by uenro** [fizvlad/vk-music-rb#5]
Is there a way to download audios using proxy?
For example I want to download audios from several posts:
audios1 = client.post("https://vk.com/wall-4790861_5453")
audios1 = client.post("https://vk.com/wall-4790861_5458")
Can I add parameters for proxy for every post? This way for example:
audios = client.post("https://vk.com/wall-4790861_5453", type: "socks5", url: "192.168.0.3")

Or is it neccessary to specify proxy here?
client = VkMusic::Client.new(username: "+71234567890", password: "password", type: "socks5", url: "192.168.0.3")

P.S. I heard that VK audio urls are linked with clients IP but there is no confirmation that audio url is linked with certain user.

**Comment by fizvlad** [comment]
Yeah, some audios might be blocked in several regions (it seems that it is best to use Moscow IP)

[Mechanize library](https://github.com/sparklemotion/mechanize) is used to send requests, so it is possible to use HTTP proxy by calling [set_proxy](http://docs.seattlerb.org/mechanize/Mechanize.html#method-i-set_proxy) method after creating of Mechanize agent.

Honestly, I currently spend most of my time on university, so you are welcome to create pull requests :)

**Comment by fizvlad** [comment]
[Mechanize#set_proxy](http://docs.seattlerb.org/mechanize/Mechanize.html#method-i-set_proxy)
```ruby
client = VkMusic::Client.new(username: "+79991234567", password: "password")
client.agent.set_proxy(address, port, user, password)
```
